name: update-confluence-page-content
description: You can update page of JIRA Confluence.
author: santsamu
inputs:
  pageId:
    description: Jira Confluence Page ID
    required: true
  pageTitle:
    description: Jira Confluence Page Title
    required: true
  appendContents:
    description: Append Content
    required: true
  contentsJson:
    description: What To Edit On The Jira Confluence Page
    default: ""
    required: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: edit
  color: blue
